# Generated by Django 4.2.11 on 2026-02-09 10:39

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الشركة')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='الشعار')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الضريبة (%)')),
                ('tax_name', models.CharField(blank=True, default='VAT', max_length=50, verbose_name='اسم الضريبة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخطة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('max_users', models.IntegerField(default=5, verbose_name='الحد الأقصى للمستخدمين')),
                ('max_products', models.IntegerField(default=100, verbose_name='الحد الأقصى للمنتجات')),
                ('has_inventory', models.BooleanField(default=True, verbose_name='يتضمن المخزون')),
                ('has_pos', models.BooleanField(default=True, verbose_name='يتضمن نقطة البيع')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر الشهري')),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر السنوي')),
                ('trial_days', models.IntegerField(default=14, verbose_name='أيام الفترة التجريبية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'خطة الاشتراك',
                'verbose_name_plural': 'خطط الاشتراك',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('trial', 'تجريبي'), ('active', 'نشط'), ('expired', 'منتهي'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('trial_end_date', models.DateField(blank=True, null=True, verbose_name='نهاية الفترة التجريبية')),
                ('payment_verified', models.BooleanField(default=False, verbose_name='تم التحقق من الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.company', verbose_name='الشركة')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='accounts.subscriptionplan', verbose_name='الخطة')),
            ],
            options={
                'verbose_name': 'اشتراك الشركة',
                'verbose_name_plural': 'اشتراكات الشركات',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('platform_manager', 'مدير المنصة'), ('company_manager', 'مدير الشركة'), ('accountant', 'محاسب'), ('representative', 'مندوب'), ('cashier', 'كاشير')], default='representative', max_length=20, verbose_name='الدور')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('products_count', models.IntegerField(default=0, verbose_name='عدد المنتجات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.company', verbose_name='الشركة')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمين',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
