# Generated by Django 4.2.11 on 2026-02-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tax_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل الضريبة'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي'),
        ),
    ]
