# Generated by Django 4.2.11 on 2026-02-09 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(default=pos.models.generate_receipt_number, max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف العميل')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المجموع الفرعي')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الخصم')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الضريبة')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الإجمالي')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة'), ('transfer', 'تحويل')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('change', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الباقي')),
                ('status', models.CharField(choices=[('completed', 'مكتمل'), ('refunded', 'مسترد'), ('cancelled', 'ملغي')], default='completed', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البيع')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='الكاشير')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'عملية بيع',
                'verbose_name_plural': 'عمليات البيع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='التكلفة')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.product', verbose_name='المنتج')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.sale', verbose_name='عملية البيع')),
            ],
            options={
                'verbose_name': 'عنصر بيع',
                'verbose_name_plural': 'عناصر البيع',
            },
        ),
    ]
