# Generated by Django 6.0.2 on 2026-02-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق'), ('approved', 'موافق'), ('rejected', 'مرفوض')], default='pending', max_length=10),
        ),
    ]
