# Generated by Django 5.2.8 on 2025-12-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'مشرف'), ('merchant', 'تاجر'), ('representative', 'مندوب')], default=('admin', 'مشرف'), max_length=20),
        ),
    ]
