# Generated by Django 4.2.11 on 2025-12-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'مشرف'), ('merchant', 'تاجر'), ('representative', 'مندوب')], default='admin', max_length=20),
        ),
    ]
