# Generated by Django 5.2.8 on 2025-12-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='products_count',
            field=models.IntegerField(default=0),
        ),
    ]
